### ISSUE TITLE
Error in match_barcodes

### ISSUE THREAD

**Issue by PaulNueh** [jgraving/pinpoint#3]
We get an error in match_barcodes while tracking, in line 677 utils.py:

`best_id_list = id_list[index]`

Probably when the last barcode of the barcode list is detected, since index always exceeds the size of the id_list (by 2). This could possibly affect also the matching for other barcodes, if all indeces are wrong.

`best_id_list = id_list[index - 2]`

prevents the error, but obviously the ids are wrong because of this. I guess videos get sometimes tracked without an error, because the tag with the last id is never detected, but in these videos, ids are still wrong. We couldn't track any video with reasonable results in the last few days (using different tags and pinpoint 0.2-dev and the newest).

**Comment by jgraving** [comment]
I'm unable to reproduce this behavior. Can you provide more details as well as a minimal working example reproducing the error? I'm also unsure how this is possible since the values of `index` provided by the `NearestNeighbors` class can only ever be `<len(id_list)`.

**Comment by PaulNueh** [comment]
Video and barcodes:
[https://we.tl/2SlUuZyOZN](url)

We tracked with following parameters:

from pinpoint import Tracker, VideoReader

videopath = ''
videofile = 'marc_calliurus_20180227_162022.mp4'

tracker = Tracker(source=videopath+videofile,
                  block_size=201,
                  offset=-15,
                  distance_threshold=20,
                  area_range=(50, 800),
                  tolerance=0.1,
                  channel='gray',
                  resize=2)

tracker.load_dict('3x3.pkl')

tracker.track('calliurus_tracks_270218_162022.h5',batch_size=200, n_jobs=-1)

**Comment by jgraving** [comment]
The latest commit update should fix this bug for custom generated dictionaries. Unfortunately any custom dictionaries generated with the bug are not usable.
